services:
  web:
    image: nginx
    ports:
      - 81:80
    volumes:
      - /home/kezhik/projects/online-shop/docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /home/kezhik/projects/online-shop/src/public:/var/www/html

  php-fpm:
    build: ./docker/php
    volumes:
      - /home/kezhik/projects/online-shop/src/public:/var/www/html

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 54322:5432